RailsTube/config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/home', to: 'static_pages#home'
  get '/signup', to: 'users#new'
  resources :users, only: [:new, :create, :show]
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
end

RailsTube/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

RailsTube/app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    
    has_secure_password

    validates :name, presence: true, length: { maximum: 30 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
    validates :password, presence: true, length: { minimum: 6 }
end

RailsTube/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

RailsTube/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      reset_session
      log_in(user)
      redirect_to user_path(user)
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

RailsTube/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def short
  end

  def channels
  end
end

RailsTube/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # エラーメッセージは未実装
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

RailsTube/app/helpers/application_helper.rb
module ApplicationHelper
end

RailsTube/app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
      session[:user_id] = user.id
    end
  
    def current_user
      if session[:user_id]
        @current_user ||= User.find_by(id: session[:user_id])
      end
    end
  
    def logged_in?
      !current_user.nil?
    end
  
    def log_out
      session.delete(:user_id)
      @current_user = nil
    end
  end
  

RailsTube/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

RailsTube/app/helpers/users_helper.rb
module UsersHelper
end

RailsTube/app/views/layouts/_header.html.erb
<header>
  <nav>
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <% if logged_in? %>
        <li><%= link_to "Profile", current_user %></li>
        <li><%= link_to "Log out", logout_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Log in", login_path %></li>
        <li><%= link_to "Sign up", signup_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

RailsTube/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTube</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |key, value| %>
      <div class="flash <%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

RailsTube/app/views/static_pages/channels.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>

RailsTube/app/views/static_pages/home.html.erb
<h1>Welcome to homepage clone!</h1>
<p>Find me in app/views/static_pages/home.html.erb!</p>

RailsTube/app/views/static_pages/short.html.erb
<h1>StaticPages#short</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>

RailsTube/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

RailsTube/app/views/users/new.html.erb
<%= form_with(model: @user) do |f| %>
  <%= f.label(:name, '名前') %>
  <%= f.text_field(:name) %>
  <%= f.label(:email, 'Email')%>
  <%= f.email_field(:email) %>
  <%= f.label(:password, 'パスワード') %>
  <%= f.password_field(:password) %>
  <%= f.label(:password_confirmation, 'パスワード確認')%>
  <%= f.password_field(:password_confirmation)%>
  <%= f.submit("アカウントを作成")%>
<% end %>

RailsTube/app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>